version: 2

project_name: stash

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - id: "stash"
    binary: "stash"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: amd64
    main: main.go
    ldflags:
      - -s -w -X main.version={{.Version}}
  - id: "stash-compat"
    binary: "stash"
    env:
      - CGO_ENABLED=0
      - GOTOOLCHAIN=go1.24.12
    goos:
      - darwin
    goarch:
      - amd64
    main: main.go
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - id: "archive"
    ids:
      - stash
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

  - id: "archive-legacy"
    ids:
      - stash-compat
    formats: ["tar.gz"]
    name_template: "stash-compat_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge"

release:
  github:
    owner: huffmanks
    name: stash
  draft: false
  prerelease: auto
  footer: >-
    ---
    Built with ❤️ using GoReleaser.
