version: 2

project_name: stash

before:
  hooks:
    - make clean
    - go mod tidy

builds:
  - id: "stash"
    binary: "stash"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: main.go
    ldflags:
      - -s -w -X github.com/huffmanks/stash/internal/config.Version={{.Tag}}

archives:
  - id: "archive"
    ids:
      - stash
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE*

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "merge"

release:
  github:
    owner: huffmanks
    name: stash
  draft: false
  prerelease: auto
  footer: >-
    ---
    Built with ❤️ using GoReleaser.
